project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "Equity, diversity and inclusion at the Behaviour 2023 Congress"
  author: "Rebecca S. Chen"
  favicon: data/logo_behaviour_nobackground_notext.png
  chapters:
    - index.qmd
    - qmd/1_summary_identities.qmd
    - qmd/2_question_asking_general.qmd
    - qmd/3_question_asking_per_age.qmd
    - qmd/4_question_asking_how.qmd
    - qmd/5_question_asking_why.qmd
    - qmd/6_question_experiment.qmd
    - qmd/7_congress_experience.qmd
    - qmd/8_perception_issues.qmd
    - qmd/9_other_gender_disparity.qmd
    - qmd/10_additional_documents.qmd
  navbar:
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

